service: stock-screener-scraper

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  timeout: 60
  memorySize: 1024

functions:
  api:
    handler: src/handler.api
    events:
      - httpApi:
          path: /screener
          method: POST
      - httpApi:
          path: /screener
          method: OPTIONS

plugins:
  - serverless-plugin-typescript

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.json'

