service: stock-screener-scraper

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  timeout: 300
  memorySize: 3008
  environment:
    NODE_ENV: production

functions:
  api:
    handler: src/handler.api
    # ðŸ‘‡ This creates a Lambda Function URL (no API Gateway)
    url:
      cors: true                    # enables CORS
      invokeMode: RESPONSE_STREAM   # enables streaming - keeps Lambda alive after response

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    external:
      - "@sparticuz/chromium"
