services:
  db:
    image: postgres # Uses the official PostgreSQL image
    container_name: simulations-db # Names the container for easy reference
    restart: always # Automatically restarts the container if it stops
    environment:
      POSTGRES_USER: admin # Sets the database user to 'admin'
      POSTGRES_PASSWORD: admin # Sets the database password to 'admin'
      POSTGRES_DB: simulations_db # Creates a database named 'next_app_localhost_db'
    ports:
      - '5432:5432' # Exposes port 5432 to the host
    volumes:
      - ./data:/var/lib/postgresql/data # Persists data to the './data' folder
